runtime: nodejs14

env_variables:
  QUEUE_NAME: "teste-email"
  QUEUE_LOCATION: "us-central1"
  FUNCTION_URL: "https://us-central1-teste-filas.cloudfunctions.net/enviarEmail"
  SERVICE_ACCOUNT_EMAIL: "firebase-adminsdk-tru3v@teste-filas.iam.gserviceaccount.com"

# Handlers for serving the index page.
handlers:
  - url: /static
    static_dir: static
  - url: /
    static_files: index.html
    upload: index.html